### ISSUE TITLE
动态数据赋值给子组件时，不能正确显示

### ISSUE THREAD

**Issue by Jeson-chen** [yimogit/vue-layui#2]
首先感谢作者造的轮子。

在用单选框等需要动态赋值，如单选框的数据（如demo中model下SelectValue）来自后台，传值给子组件时，因为子组件没用监听改变，导致单向不能被选中。
作者的例子并不会造成如上问题，是因为作者例子的数据是静态数据。
建议在YmSelect等子模版中写watch来监听，这样在编辑数据时，就不会出现问题

**Comment by yimogit** [comment]
感谢反馈，这一版其实有很多的问题，是作为一个自己学习的过程，不建议使用甚至参考。
最近我找时间重写下，把一些在项目中使用的经验融入进来。
